# Generated by Django 5.0.3 on 2024-04-06 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuitionapp', '0002_alter_customuser_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermember',
            old_name='number',
            new_name='contact',
        ),
        migrations.AddField(
            model_name='usermember',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tuitionapp.course'),
        ),
    ]
