# Generated by Django 5.0.3 on 2024-04-07 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuitionapp', '0003_rename_number_usermember_contact_usermember_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermember',
            name='gender',
        ),
        migrations.AlterField(
            model_name='usermember',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
