# Generated by Django 5.0.3 on 2024-04-08 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuitionapp', '0005_studentattendance_teacherattendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='current_teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_teacher_courses', to=settings.AUTH_USER_MODEL),
        ),
    ]
