# Generated by Django 5.0.3 on 2024-04-09 06:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuitionapp', '0011_remove_course_current_teacher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermember',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_student_assignment', to=settings.AUTH_USER_MODEL),
        ),
    ]
