# Generated by Django 5.0.3 on 2024-04-09 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuitionapp', '0013_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='syllabus',
            field=models.FileField(upload_to='syllabus_pdfs/'),
        ),
    ]
