# Generated by Django 5.0.3 on 2024-04-11 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tuitionapp', '0015_task_assigned_by_tasksubmission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='assigned_by',
            new_name='assigned_to',
        ),
    ]
