# Generated by Django 5.0.3 on 2024-04-11 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tuitionapp', '0016_rename_assigned_by_task_assigned_to'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='assigned_to',
            new_name='teacher',
        ),
    ]
