# Generated by Django 5.0.3 on 2024-04-11 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuitionapp', '0017_rename_assigned_to_task_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tuitionapp.usermember'),
        ),
    ]
