# Generated by Django 5.0.3 on 2024-04-11 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tuitionapp', '0018_alter_task_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='teacher',
        ),
    ]
