# Generated by Django 5.0.3 on 2024-04-11 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuitionapp', '0020_task_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksubmission',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
