# Generated by Django 5.0.3 on 2024-04-11 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tuitionapp', '0022_tasksubmission_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasksubmission',
            old_name='student',
            new_name='student_id',
        ),
    ]
