# Generated by Django 5.0.3 on 2024-04-11 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tuitionapp', '0023_rename_student_tasksubmission_student_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasksubmission',
            old_name='student_id',
            new_name='student',
        ),
    ]
