from django.urls import path
from . import views

urlpatterns = [
    path('',views.home,name='home'),
    path('login1',views.login1,name='login1'),
    path('login_user',views.login_user,name='login_user'),
    path('t_reg',views.t_reg,name='t_reg'),
    path('s_reg',views.s_reg,name='s_reg'),
    path('adminhome',views.adminhome,name='adminhome'),
    path('course',views.course,name='course'),
    path('add_course',views.add_course,name='add_course'),
    path('view_course',views.view_course,name='view_course'),
    # path('edit_course/<int:pk>',views.edit_course,name='edit_course'),
    # path('edit_course1/<int:pk>/', views.edit_course1, name='edit_course1'),
    # path('delete_course/<int:pk>',views.delete_course,name='delete_course'),
    path('logout1',views.logout1,name='logout1'),
    path('sregistration',views.sregistration,name='sregistration'),
    path('tregistration',views.tregistration,name='tregistration'),
    path('approve_disapprove',views.approve_disapprove,name='approve_disapprove'),
    path('approve/<int:pk>',views.approve,name='approve'),
    path('disapprove/<int:pk>',views.disapprove,name='disapprove'),
    path('show_teacher',views.show_teacher,name='show_teacher'),
    path('show_student',views.show_student,name='show_student'),
    path('delete_teacher/<int:pk>/', views.delete_teacher, name='delete_teacher'),
    path('delete_student/<int:pk>',views.delete_student,name='delete_student'),
    path('add_tattendance',views.add_tattendance,name='add_tattendance'),
    path('teach_attend',views.teach_attend,name='teach_attend'),
    path('view_tattendance',views.view_tattendance,name='view_tattendance'),
    path('view_teacher_attendance',views.view_teacher_attendance,name='view_teacher_attendance'),
    path('view_teacher_attendance_list',views.view_teacher_attendance_list,name='view_teacher_attendance_list'),
    path('assign', views.assign, name='assign'),
    path('assign_teacher/<int:student_id>/<int:teacher_id>/',views.assign_teacher,name='assign_teacher'),
    path('teacherhome',views.teacherhome,name='teacherhome'),
    path('attend_teach',views.attend_teach,name='attend_teach'),
    path('show_teacher_attendance/', views.show_teacher_attendance_list, name='show_teacher_attendance_list'),
    path('view_syllabus',views.view_syllabus,name='view_syllabus'),
    path('add_sattendance',views.add_sattendance,name='add_sattendance'),
    path('stud_attend',views.stud_attend,name='stud_attend'),
    path('view_sattendance',views.view_sattendance,name='view_sattendance'),
    path('view_student_attendance',views.view_student_attendance,name='view_student_attendance'),
    path('view_student_attendance_list',views.view_student_attendance_list,name='view_student_attendance_list'),
    path(' teach_view_student',views. teach_view_student,name=' teach_view_student'),
    path('task',views.task,name='task'),
    path('assign_task',views.assign_task,name='assign_task'),
    path('studenthome',views.studenthome,name='studenthome'),
    path('attend_stud',views.attend_stud,name='attend_stud'),
    path('show_student_attendance/', views.show_student_attendance_list, name='show_student_attendance_list'),
    path('view_syllabus_stud',views.view_syllabus_stud,name='view_syllabus_stud'),
    path('view_studattendance',views.view_studattendance,name='view_studattendance'),
    path('view_stud_attendance',views.view_stud_attendance,name='view_stud_attendance'),
    path('view_all_student_attendance_list',views.view_all_student_attendance_list,name='view_all_student_attendance_list'),
    path('course_view',views.course_view,name='course_view'),
    path('profile',views.profile,name='profile'),
    path('edit_pro', views.edit_pro, name='edit_pro'),
    path('edit_profile', views.edit_profile, name='edit_profile'),
    path('reset_password_stud', views.reset_password_stud, name='reset_password_stud'),
    path('view_task',views.view_task,name='view_task'),
    path('student_task_view',views.student_task_view,name='student_task_view'),
    path('view_uploaded_tasks',views.view_uploaded_tasks,name='view_uploaded_tasks'),
    path('task_submit/<int:task_id>/',views.task_submit,name='task_submit'),
    path('submit_task/<int:task_id>/', views.submit_task, name='submit_task'),
    path('reset_password',views.reset_password,name='reset_password'),
    path('reset_password_teach', views.reset_password_teach, name='reset_password_teach'),
    path('reset_password1',views.reset_password1,name='reset_password1'),
]

   
